# Generated by Django 3.0.2 on 2020-01-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('unidade', models.CharField(default='uni', max_length=10)),
                ('validade', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
